version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest-16
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./environment/node-red/data:/data

networks:
  node-red-net: