version: "3.7"

services:
  node-red:
    build:
      context: environment/node-red
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./environment/node-red/data:/data

networks:
  node-red-net: